runtime: python310
env: standard
instance_class: F1
default_expiration: "4d 5h"
automatic_scaling:    
    max_instances: 1
    max_idle_instances: 1

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301